Repository tmax-cloud/cicd-operator, pull requests merged in 2021-12, with the labels that each got.

#311 [bugfix] Fix incorrect logr usage
  pkg/cron/cron.go
Labels: approved, size/XS

#313 [bugfix] Fix the incorrect conditional statement
  controllers/integrationconfig_controller.go
Labels: approved, size/XS

#314 [feat] Enable timeout for IntegrationJob
  api/v1/integrationconfig_types.go
  api/v1/integrationjob_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/cicd.tmax.io_integrationconfigs.yaml
  config/crd/cicd.tmax.io_integrationjobs.yaml
  config/release.yaml
  pkg/dispatcher/dispatcher.go
  pkg/periodictrigger/periodic_trigger.go
  pkg/pipelinemanager/pipelinemanager.go
  pkg/scheduler/pool/pool.go
  pkg/scheduler/pool/pool_test.go
  pkg/scheduler/scheduler.go
Labels: approved, size/L

#312 [chore] Add periodic example
  examples/14-periodic-job-using-tekton-task.yaml
Labels: approved, size/M

#315 [test] Add timeout related test code
  api/v1/integrationconfig_types_test.go
  docs/integration_config.md
  pkg/dispatcher/dispatcher_test.go
Labels: approved, size/L

#316 [chore] Avoid using default service account
  config/blocker/blocker.yaml
  config/controller/controller.yaml
  config/rbac/role_binding.yaml
  config/rbac/service_account.yaml
  config/release.yaml
  hack/release-manifest.sh
Labels: approved, size/S

#318 [feat] Support conditional execution
  api/v1/integrationconfig_types.go
  api/v1/integrationjob_types.go
  api/v1/job_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/cicd.tmax.io_integrationconfigs.yaml
  config/crd/cicd.tmax.io_integrationjobs.yaml
  config/release.yaml
  pkg/dispatcher/dispatcher.go
  pkg/periodictrigger/periodic_trigger.go
  pkg/pipelinemanager/pipelinemanager.go
  pkg/pipelinemanager/tektonTasks.go
Labels: approved, size/XL

#319 [test] Add tekton param test
  api/v1/integrationjob_types_test.go
Labels: approved, size/M

#320 [chore] Update integration_config.md
  docs/integration_config.md
  examples/15-job-using-tekton-when.yaml
Labels: approved, size/L

#321 [chore] Bump version to v0.5.1
  Makefile
  config/release.yaml
Labels: approved, size/XS

#322 [chore] Update i18n CRD manifests
  config/crd-key-mapping/cicd.tmax.io_approvals.yaml
  config/crd-key-mapping/cicd.tmax.io_integrationconfigs.yaml
  config/crd-key-mapping/cicd.tmax.io_integrationjobs.yaml
Labels: approved, size/XXL

#323 [fix] Fix ingress annotation nil error
  controllers/expose_controller.go
  controllers/expose_controller_test.go
Labels: size/S

#324 [fix] Fix parameter get error
  api/v1/integrationconfig_types_test.go
  api/v1/integrationjob_types_test.go
  pkg/pipelinemanager/pipelinemanager.go
  pkg/pipelinemanager/pipelinemanager_test.go
Labels: approved, size/L

#325 [feat] Support insecure skip verify
  api/v1/integrationconfig_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/cicd.tmax.io_integrationconfigs.yaml
  config/release.yaml
  docs/integration_config.md
  pkg/git/github/github.go
  pkg/git/gitlab/gitlab.go
  pkg/git/http.go
Labels: approved, size/L
