Repository tmax-cloud/cicd-operator, pull requests merged in 2021-07, with the labels that each got.

#231 [chore] Add CRD for i18n
  config/crd-key-mapping/cicd.tmax.io_approvals.yaml
  config/crd-key-mapping/cicd.tmax.io_integrationconfigs.yaml
  config/crd-key-mapping/cicd.tmax.io_integrationjobs.yaml
Labels: approved

#230 [fix] Invalidate pr pool cache if new commit is added
  pkg/blocker/blocker.go
  pkg/blocker/sync_pool.go
Labels: approved

#229 [fix] Authorize setter of 'approved' label
  cmd/controller/main.go
  docs/quickstart.md
  pkg/chatops/plugins/approve/handlers_approve.go
  pkg/git/git_types.go
  pkg/git/github/parser.go
  pkg/git/github/webhook.go
  pkg/git/gitlab/parser.go
  pkg/git/gitlab/webhook.go
Labels: approved

#233 [chore] Bump version to v0.3.1
  Makefile
  config/release.yaml
  docs/installation.md
Labels: approved

#234 [fix] Add health and readiness probe to pods
  cmd/blocker/main.go
  cmd/controller/main.go
  config/blocker/blocker.yaml
  config/controller/controller.yaml
  config/release.yaml
  docs/installation.md
Labels: approved

#239 [docs] Add missing fields
  docs/configs.md
Labels: approved

#240 [chore] Add email notification and mergeConfig for cicd.yaml
  cicd.yaml
Labels: approved

#245 [fix] Change approval plugin's target event type
  go.mod
  go.sum
  pkg/chatops/plugins/approve/handlers_approve.go
  pkg/chatops/plugins/approve/handlers_approve_test.go
Labels: approved

#249 [fix] Request merge without title, message field if they're empty
  pkg/git/github/github_types.go
  pkg/git/gitlab/gitlab_types.go
Labels: approved

#248 [feat] Add size plugin
  cmd/controller/main.go
  config/controller/controller.yaml
  config/release.yaml
  docs/plugins/size.md
  internal/configs/plugins.go
  internal/configs/plugins_test.go
  pkg/plugins/size/size.go
  pkg/plugins/size/size_test.go
Labels: approved

#252 [fix] Set approval sender name as annotation, not label
  controllers/approval_controller.go
Labels: approved, size/S

#254 [docs] Fix blocker configuration docs
  docs/config_blocker.md
Labels: approved, size/XS

#253 [feat] Add hold plugin
  cmd/controller/main.go
  docs/chat-commands.md
  docs/plugins/hold.md
  internal/configs/blocker.go
  internal/configs/blocker_test.go
  pkg/chatops/plugins/hold/handlers_hold.go
  pkg/chatops/plugins/hold/handlers_hold_test.go
Labels: approved, size/L

#256 [docs] Add example yamls
  examples/00-git-token.yaml
  examples/01-hello-world.yaml
  examples/01-public-git.yaml
  examples/03-after-when-filter.yaml
  examples/04-approval-job.yaml
  examples/05-notification-job.yaml
  examples/06-notification-succeed-or-fail.yaml
  examples/07-job-using-tekton-task.yaml
  examples/08-build-and-push-image-using-credential-secret.yaml
  examples/09-without-git-token.yaml
  examples/10-using-workspaces-between-jobs.yaml
  examples/11-using-workspaces-inside-a-job.yaml
  examples/12-make-k8s-resource-and-role-binding.yaml
  examples/13-merge-automation.yaml
Labels: approved, size/XL

#251 [feat] Support batch test using IntegrationJob
  pkg/blocker/merge.go
  pkg/blocker/merge_test.go
  pkg/git/github/parser.go
Labels: approved, size/M

#257 [fix] Copy Approval status to Run status
  controllers/customs/approval_run_controller.go
  controllers/customs/approval_run_controller_test.go
Labels: approved, size/L

#258 [fix] Change Waiting status to Awaiting status
  api/v1/approval_types.go
  controllers/approval_controller.go
  controllers/customs/approval_run_controller.go
  controllers/customs/approval_run_controller_test.go
  controllers/customs/email_run_controller.go
  controllers/customs/slack_run_controller.go
Labels: approved, size/S

#259 [docs] Add swagger-ui document for IntegrationConfig releated apis
  docs/swagger/approval.yaml
  docs/swagger/integrationconfig.yaml
Labels: approved, size/L
