Repository tmax-cloud/cicd-operator, pull requests merged in 2022-04, with the labels that each got.

#352 [test] Add github test codes
  pkg/git/git.go
  pkg/git/github/github_test.go
Labels: approved, size/L

#353 [fix] Fix taskrun status sync with IJ status
  pkg/pipelinemanager/pipelinemanager.go
Labels: approved, size/XS

#356 [feat] support logging requestbody
  .github/workflows/main.yaml
  .golangci.yaml
  api/v1/integrationconfig_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/cicd.tmax.io_integrationconfigs.yaml
  config/release.yaml
  docs/integration_config.md
  pkg/server/handler_webhook.go
Labels: size/L
