Repository tmax-cloud/cicd-operator, pull requests merged in 2022-05, with the labels that each got.

#358 [feat] Enable TLS configuration
  api/v1/integrationconfig_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/cicd.tmax.io_integrationconfigs.yaml
  config/release.yaml
  pkg/git/github/github.go
  pkg/git/gitlab/gitlab.go
  pkg/git/http.go
Labels: approved, size/L

#359 [feat] set default branch for jobs to be applied to
  api/v1/integrationconfig_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/cicd.tmax.io_integrationconfigs.yaml
  config/release.yaml
  docs/integration_config.md
  pkg/blocker/merge.go
  pkg/dispatcher/dispatcher.go
Labels: approved, size/M

#363 [Fix] support git insecure option
  pkg/pipelinemanager/step_git_checkout.go
Labels: approved, size/S
