Repository tmax-cloud/cicd-operator, pull requests merged in 2022-03, with the labels that each got.

#346 [chore] Workflow for v0.4.3 branch
  .github/workflows/main.yaml
Labels: approved, size/XS

#340 [feat] Support custom tetkon catalog
  docs/integration_config.md
  pkg/pipelinemanager/pipelinemanager.go
  pkg/pipelinemanager/pipelinemanager_test.go
  pkg/pipelinemanager/tektonTasks.go
  pkg/pipelinemanager/tektonTasks_test.go
Labels: approved, size/L

#347 [feat] Enable commit comment chat-ops
  cmd/webhook/main.go
  docs/chat-commands.md
  docs/integration_config.md
  pkg/chatops/plugins/approve/handlers_approve.go
  pkg/chatops/plugins/hold/handlers_hold.go
  pkg/chatops/plugins/trigger/handlers_trigger.go
  pkg/dispatcher/dispatcher.go
  pkg/git/fake/fake.go
  pkg/git/git.go
  pkg/git/git_types.go
  pkg/git/github/github.go
  pkg/git/github/parser.go
  pkg/git/github/webhook.go
  pkg/git/gitlab/gitlab.go
  pkg/git/gitlab/gitlab_types.go
  pkg/git/gitlab/parser.go
  pkg/git/gitlab/webhook.go
  pkg/pipelinemanager/step_git_checkout.go
Labels: approved, size/L

#349 [chore] Bump version to v0.5.3
  Makefile
  config/release.yaml
  go.mod
  go.sum
Labels: size/M

#351 [test] Add test codes
  .github/workflows/main.yaml
  api/v1/integrationconfig_types_test.go
  api/v1/integrationjob_types_test.go
  pkg/git/github/github.go
  pkg/git/github/github_test.go
Labels: approved, size/L
