Repository tmax-cloud/cicd-operator, pull requests merged in 2022-08, with the labels that each got.

#369 [fix] OOM kill during git-checkout
  internal/configs/controller.go
  pkg/pipelinemanager/step_git_checkout.go
Labels: size/S

#372 [fix] golangci workflow
  .github/workflows/main.yaml
Labels: size/L

#370 [fix] fix taskrun status sync with IJ status
  pkg/pipelinemanager/pipelinemanager.go
Labels: size/XS

#374 [feat] support logging requestbody
  api/v1/integrationconfig_types.go
  config/crd/cicd.tmax.io_integrationconfigs.yaml
  docs/integration_config.md
  pkg/server/handler_webhook.go
Labels: size/S

#376 [fix] golangci workflow
  .github/workflows/main.yaml
  .golangci.yaml
Labels: size/S

#377 [feat] add noti method using Webhook
  Makefile
  api/v1/custom_tasks.go
  api/v1/integrationconfig_types.go
  api/v1/noti_types.go
  api/v1/zz_generated.deepcopy.go
  cmd/controller/main.go
  config/crd/cicd.tmax.io_integrationconfigs.yaml
  config/crd/cicd.tmax.io_integrationjobs.yaml
  controllers/customs/webhook_controller.go
  docs/integration_config.md
  docs/notification-jobs.md
  hack/release-manifest.sh
  pkg/dispatcher/dispatcher.go
  pkg/notification/webhook/webhook.go
  pkg/notification/webhook/webhook_test.go
  pkg/notification/webhook/webhook_type.go
  pkg/pipelinemanager/custom_runs.go
  pkg/pipelinemanager/notification.go
  pkg/pipelinemanager/pipelinemanager.go
Labels: size/XL

#379 [feat] set default branch for jobs to be applied to
  api/v1/integrationconfig_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/cicd.tmax.io_integrationconfigs.yaml
  docs/integration_config.md
  pkg/blocker/merge.go
  pkg/dispatcher/dispatcher.go
Labels: approved, size/M
