Repository tmax-cloud/cicd-operator, pull requests merged in 2022-09, with the labels that each got.

#380 [fix] support git insecure option
  pkg/pipelinemanager/step_git_checkout.go
Labels: approved, size/XS

#382 [fix] unable to fetch variables
  api/v1/noti_types.go
  controllers/customs/webhook_controller.go
  pkg/pipelinemanager/custom_runs.go
Labels: size/S

#383 [fix] unable to fetch variable when sending notification
  Makefile
  go.mod
  go.sum
  pkg/pipelinemanager/custom_runs.go
Labels: size/S

#386 [Feat] support logging requestbody in taskRun pod
  pkg/dispatcher/dispatcher.go
  pkg/git/git_types.go
  pkg/git/github/parser.go
  pkg/git/gitlab/parser.go
  pkg/pipelinemanager/env.go
Labels: approved

#387 [chore] enable to set log level
  cmd/apiserver/main.go
  cmd/blocker/main.go
  cmd/controller/main.go
  cmd/webhook/main.go
  docs/installation.md
Labels: size/M

#388 [feat] create pipeline if not exists
  Makefile
  config/release.yaml
  controllers/integrationjob_controller_test.go
  go.mod
  go.sum
  pkg/pipelinemanager/pipelinemanager.go
  pkg/pipelinemanager/pipelinemanager_test.go
  pkg/scheduler/scheduler.go
Labels: size/L

#390 [fix] rbac for pipelines
  config/rbac/role.yaml
Labels: size/XS

#392 [fix] rbac for pipeline
  config/rbac/role.yaml
  config/release.yaml
  controllers/integrationjob_controller.go
Labels: size/S
